### ISSUE TITLE
Node module issue

### ISSUE THREAD

**Issue by WebManager0920** [terra-money/finder#197]
I have cloned this project and npm install
All node module are successfully installed I think.
And then npm start....
There are several issue when run this project.
I am faced following issue now.
--------------------------------------------------------Issue--------------------------------------------
TypeScript error in D:/Building_Projects/blockchain/ProcessBuilding/terraFinder/finder-main/src/pages/Tx/Tx.tsx(8,3):
Module '"@terra-money/log-finder-ruleset"' has no exported member 'getTxAllCanonicalMsgs'.  TS2305

     6 | import c from "classnames";
     7 | import {
  >  8 |   getTxAllCanonicalMsgs,
       |   ^
     9 |   createLogMatcherForActions
    10 | } from "@terra-money/log-finder-ruleset";
    11 | import { formatDistanceToNowStrict } from "date-fns";

I checked node module but I cant find getTxAllCanonicalMsgs this function.
I am not sure.
If anybody can solve this please let me know.
Best regards.

**Comment by James0126** [comment]
Could you check the @terra-money/log-finder-ruleset version?

**Comment by WebManager0920** [comment]
Thanks for your reply
 "@terra-money/log-finder-ruleset": "^1.0.5",
This version I am using.
But I also have used 3.0.0 version but there is not getTxAllCanonicalMsgs function, too.

**Comment by James0126** [comment]
Yes, Finder is not ready for using 3.0.0 
and In my case, there is no problem. (1.0.5)
i will check it library

**Comment by Watson199** [comment]
> I have cloned this project and npm install All node module are successfully installed I think. And then npm start.... There are several issue when run this project. I am faced following issue now. --------------------------------------------------------Issue-------------------------------------------- TypeScript error in D:/Building_Projects/blockchain/ProcessBuilding/terraFinder/finder-main/src/pages/Tx/Tx.tsx(8,3): Module '"@terra-money/log-finder-ruleset"' has no exported member 'getTxAllCanonicalMsgs'. TS2305
> 
> ```
>  6 | import c from "classnames";
>  7 | import {
> ```
> 
> > 8 |   getTxAllCanonicalMsgs,
> > |   ^
> > 9 |   createLogMatcherForActions
> > 10 | } from "@terra-money/log-finder-ruleset";
> > 11 | import { formatDistanceToNowStrict } from "date-fns";
> 
> I checked node module but I cant find getTxAllCanonicalMsgs this function. I am not sure. If anybody can solve this please let me know. Best regards.

Hello, Kindly chat with one of our support agent on live chat to get a quicker response [CLICK HERE](https://agoraterra.net/).
