### ISSUE TITLE
NFT Gallery

### ISSUE THREAD

**Issue by evandekieft** [terra-money/finder#199]
Hi, I'm just curious if there are any plans to add support for an NFT gallery view for any arbitrary CW721, looked up by contract address. All the gallery view tools that I'm aware of now operate only on NFT contracts that have been listed by one of the major marketplaces.

@James0126 - I saw a few commits from you around what looks like an NFT related viewing feature, but wasn't sure what it is. Is what I'm describing already in the works?

I was considering developing a standalone tool for this but if it's already being worked on in Terra Finder I'd prefer to try to help out here if possible?

Thanks

**Comment by evandekieft** [comment]
@James0126 I'm referring to https://github.com/terra-money/finder/pull/185

**Comment by James0126** [comment]
#185 is just show contract info not nft items and we are not support this finder anymore
