### ISSUE TITLE
[Bug] empty transaction fee for col-3

### ISSUE THREAD

**Issue by hanjukim** [terra-money/finder#2]
## Symptom
Transaction fee for columbus-3 tx is empty

## As Is
Faucet address: _terra1h8ljdmae7lx05kjj79c9ekscwsyjd3yr8wyvdn_
Sample: https://finder.terra.money/soju-0011/tx/A12C385DA78639708D9964A2FD2005DAA74F831E6B7FE21A4319CA41F519DDEE

## To be
Fees in JSON should be shown correctly.
https://soju-fcd.terra.dev/txs/A12C385DA78639708D9964A2FD2005DAA74F831E6B7FE21A4319CA41F519DDEE

**Comment by CUI-DI** [comment]
fixed by https://github.com/terra-project/finder/commit/c5dbdf55cdad1b1938bdd95cebc35f399f71340e
