### ISSUE TITLE
Possibly Missing / Hidden Transaction

### ISSUE THREAD

**Issue by DemonRx** [terra-money/finder#214]
Please refer to https://agora.terra.money/t/proposal-burn-the-remaining-ust-in-the-community-pool-cross-chain-liquidity-incentive-ust-2/34012/94?u=demonrx

Sorry if this is not the right repository to report this issue. Decided to try here since  terra.finder is having a discrepency between what the block is reporting and what the proposal supposedly executed for the spending  proposal.

In summary, Proposal [1747](https://lcd.terra.dev/cosmos/gov/v1beta1/proposals/1747) seeks for community vote to Burn ```“amount”: “1006733194000000 uusd”```
 from the community pool.

The proposal [passed](https://lcd.terra.dev/cosmos/gov/v1beta1/proposals/1747/tally).  Block [7791896](https://lcd.terra.dev/distribution/community_pool?height=7791896) indicates the balance of the pool was reduced to:

 ```{"denom":"uusd","amount":"1577308.156297266753643322"}``` from ```{"denom":"uusd","amount":"1006733195577308.156297266304829250"}``` at prevoius Block [7791895](https://lcd.terra.dev/distribution/community_pool?height=7791895)

However, [terra.finder.money](https://finder.terra.money/mainnet/address/terra1sk06e3dyexuq4shw77y3dsv480xv42mq73anxu
) shows no transaction whatsover corraborating this "burn"/ change of balance at those  blocks or ```“voting_end_time”: “2022-05-26T19:58:17.280348372Z”```

There is no transaction showing at the burn address indicated to be used in tthe proposal: ```"recipient": "terra1sk06e3dyexuq4shw77y3dsv480xv42mq73anxu"```

 [terra1sk06e3dyexuq4shw77y3dsv480xv42mq73anxu](https://finder.terra.money/mainnet/address/terra1sk06e3dyexuq4shw77y3dsv480xv42mq73anxu
)

![07bb27ea273a5f768a2ac9d6fec83faeefac27e8](https://user-images.githubusercontent.com/18432686/170695769-bfc2939a-3df0-4a8b-9a49-3c69c9faf528.png)
First transaction occurring after passing of the proposal is almost an hour later from voting_end_time at TX ID: [1433C38E458569CF791F2E3B40295C16286FC8D541690A98FEED99462549F295](https://finder.terra.money/mainnet/tx/1433C38E458569CF791F2E3B40295C16286FC8D541690A98FEED99462549F295) this and all subsequent transactions show no burn/transfer of proposed funds.

Conclusion, how is it possible the community pool / block history is showing a change in balance but no transaction / TXID to show the burn/transfer ? 

Yet, Total / Circulating supply shows unchanged as of today: [11,278,951,456.02](https://messari.io/asset/terrausd/chart/sply-circ) vs [{"denom":"uusd","amount":"1580489.929271780077612297"}](https://lcd.terra.dev/distribution/community_pool)

**Comment by DemonRx** [comment]
Adding some more information:

The OP of the agora thread posted where the burn supposedly occurred in something he referred to as the "end block" https://agora.terra.money/t/proposal-burn-the-remaining-ust-in-the-community-pool-cross-chain-liquidity-incentive-ust-2/34012/114?u=demonrx

However, I've read into the docs about this, and understand upon a vote that passes a proposal it executes the "handler" which will automatically go into effect by directly altering the network’s specified parameter.

### Can you please explain in more detail what it means by " _directly altering the network’s specified parameter_" ?

Furthermore, why does burning/unminting supply not have a transaction viewable on the explorer ? And the burn address itself show's no record of it. How can we be sure it's actually removed ?

**Comment by Chunyingquan** [comment]
Hi I withdraw 300 thousand Luna coin from kucoin account to terra station bluna account 
And coin was missing

**Comment by hanjukim** [comment]
> Adding some more information:
> 
> The OP of the agora thread posted where the burn supposedly occurred in something he referred to as the "end block" https://agora.terra.money/t/proposal-burn-the-remaining-ust-in-the-community-pool-cross-chain-liquidity-incentive-ust-2/34012/114?u=demonrx
> 
> However, I've read into the docs about this, and understand upon a vote that passes a proposal it executes the "handler" which will automatically go into effect by directly altering the network’s specified parameter.
> 
> ### Can you please explain in more detail what it means by " _directly altering the network’s specified parameter_" ?
> Furthermore, why does burning/unminting supply not have a transaction viewable on the explorer ? And the burn address itself show's no record of it. How can we be sure it's actually removed ?

As you said, when passing the proposal, it will be processed by End Blocker without any transaction.
