### ISSUE TITLE
Error in JSON copied from Smart Contract query Result 

### ISSUE THREAD

**Issue by desamtralized** [terra-money/finder#53]
The copy button (as shown on the bottom right corner of the image below) is putting [object Object] on the clipboard. 
Calling `JSON.stringify(obj)` before putting it in the clipboard might solve it.

<img width="523" alt="Screen Shot 2021-03-04 at 1 19 08 AM" src="https://user-images.githubusercontent.com/564039/109920349-29959f00-7c88-11eb-9315-c6985a5bd2a8.png">

**Comment by ouiliame** [comment]
@simcheolhwan @James0126 please check this out
