### ISSUE TITLE
[Finder] Vodka url error for address

### ISSUE THREAD

**Issue by Freya-Shin** [terra-money/finder#6]
# Summary
Vodka url error for address
https://finder.terra.money/vodka/account/terra1wg2mlrxdmnnkkykgqg4znky86nyrtc45q336yv

# Expected
Account page for Vodka is displayed successfully.

# Environments
* Chain: soju
* OS: Windows 10

# Reproduce
1. Open 'Station' app > Sign in
2. Select 'Vodka' chain
3. Click on address link
4. Confirm the url

**Comment by hanjukim** [comment]
https://finder.terra.money/vodka-0001/... is correct
